# Generated by Django 4.2.4 on 2023-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_replay',
            new_name='is_reply',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='replay',
            new_name='reply',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=400, verbose_name='comment'),
        ),
    ]
